### Site info:
title: Homepage of ZHANG Hong 
tagline: 乘风好去, 长空万里, 直下看山河
author: H. (Hong) Zhang
email: hzhang1991@gmail.com
description: "H. Zhang's Homepage." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Hong Zhang's Homepage, 张弘的主页 "
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hzhang1991.github.io" # the base hostname & protocol for your site
locale: en_US
encoding: utf-8

### Personal info and site tools info:
twitter_username:
facebook_username: h.zhang1991
github_username:
googlescholar_username: TrB-5asAAAAJ
researchgate_username: Hong_Zhang67
disqus_shortname: hzhang1991-github-io
favicon:     "/images/favicon.ico"
aboutme: Hi, this is ZHANG Hong (张弘), a Ph.D student working in Scientific Computing in Utrecht University, the Netherlands. # these are shown on aboutme-sidebar.
aboutme_photo: http://i.imgur.com/VNyDumC.jpg #"/images/hzhang.jpg1"#https://i.imgur.com/Mdc4szJl.jpg# your photo.
google_analytics_key: UA-70088037-2 #UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr) and Russian (ru) 

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Counter:  "Read"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "Curriculum Vitae"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"
      By: "by"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Counter: "浏览量"
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
      Home: "首页"
      About: "关于"
      Guestbook: "留言"
      Subscribe: "订阅"
      By: "| 作者:"
    jp:
      Aboutme: "著者"
      Archives: "アーカイブ"
      Blogroll: "ブログロール"
      Categories: "カテゴリー"
      Copyright_Notice: "著作権表示"
      Recent_Posts: "最近の投稿"
      Tags: "タグ"
      Previous: "前の記事"
      Next: "次の記事"
      PostedInCategories: "カテゴリー："
      Taggedwith: "| タグ："
      PostDate: "| 投稿日時: "
      Google_search: "サイト内検索"
      Home: "ホーム"
      About: "このブログについて"
      Guestbook: "メッセージ"
      Subscribe: "購読"
    pl:
      Aboutme: "O mnie"
      Archives: "Archiwum"
      Blogroll: "Odnośniki"
      Categories: "Kategorie"
      Copyright_Notice: "Prawa autorskie"
      Recent_Posts: "Najnowsze wpisy"
      Tags: "Tagi"
      Previous: "Starsze"
      Next: "Nowsze"
      PostedInCategories: "Kategoria"
      Taggedwith: "tagi"
      PostDate: "on "
      Google_search: "Wyszukiwarka"
      Home: "Strona główna"
      About: "O mnie"
      Guestbook: "Księga gości"
      Subscribe: "Subskrypcja"
    kr:
      Aboutme: "저자 소개"
      Archives: "모든 게시물"
      Blogroll: "참조 링크"
      Categories: "카테고리"
      Copyright_Notice: "저작권"
      Recent_Posts: "최근 게시물"
      Tags: "태그"
      Previous: "이전 게시물"
      Next: "다음 게시물"
      PostedInCategories: "카테고리: "
      Taggedwith: "태그: "
      PostDate: "작성일: "
      Google_search: "게시물 검색"
      Home: "홈"
      About: "소개"
      Guestbook: "방명록"
      Subscribe: "구독하기"
    ru:
      Aboutme: "Обо мне" # = 'About me'
      Archives: "Архив"
      Blogroll: "Ссылки" # = 'Links'
      Categories: "Разделы"
      Copyright_Notice: "Авторские права"
      Recent_Posts: "Свежие посты"
      Tags: "Теги"
      Previous: "Предыдущий пост"          # = 'Previous post'
      Next: "Следующий пост"               # = 'Next post'
      PostedInCategories: "Опубликовано в" # = 'Posted in'
      Taggedwith: "с тегами"
      PostDate: ""
      Google_search: "Поиск на Google"
      Home: "Домой"
      About: "О блоге"            # = 'About blog'
      Guestbook: "Гостевая книга"
      Subscribe: "Подписаться"

### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: H. Zhang's  website
        href: http://hzhang1991.github.io
        title: H. (Hong) Zhang's website
      - name: H. (Hong) Zhang in Utrecht University
        href: http://www.uu.nl/staff/HZhang4
        title: Homepage of Hong Zhang
      - name: Math Calendar, Utrecht University
        href: http://utrechtgeometrycentre.nl/calendar/
        title: Math Calendar


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
excerpt_separator: <!--more-->
